version: '3.7'

services:
    beejee_nginx:
        image: nginx:1.25.1-alpine
        container_name: ${PROJECT_NAME}_nginx
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
        volumes:
            - ../:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
        depends_on:
            - beejee_php
        networks:
            beejee-network:

    beejee_php:
        build:
            context: ./php
        container_name: ${PROJECT_NAME}_php
        environment:
            APP_ENV: dev
            XDEBUG_SESSION: PHPSTORM
            XDEBUG_MODE: debug
        volumes:
            - ../:/var/www
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
        networks:
            beejee-network:

networks:
    beejee-network:
        driver: bridge