index:
  path: /
  controller: App\Controller\Home
  methods: ['GET']
  defaults:
    _action: 'handle'
    title: 'Home'

createTask:
  path: /tasks
  controller: App\Controller\Tasks
  methods: ['POST']
  defaults: { _action: 'create' }
  requirements:
    name: '\w+'

tasksList:
  path:
    /tasks/page/{page}
  controller: App\Controller\Tasks
  methods: ['GET']
  defaults:
    _action: 'list'
    page: 1
    title: 'Tasks'
  requirements:
    page: '\d+'

authPage:
  path: /auth
  controller: App\Controller\Auth
  methods: ['GET']
  defaults:
    _action: 'handle'
    title: 'Login'
    hide: ['if_authorized']

loginUser:
  path: /auth
  controller: App\Controller\Auth
  methods: ['POST']
  defaults:
    _action: 'login'

logout:
  path: /logout
  controller: App\Controller\Auth
  methods: ['GET']
  defaults:
    _action: 'logout'
    title: 'Logout'
    hide: ['if_unauthorized']
