index:
  path: /
  controller: App\Controller\Home
  methods: ['GET']
  defaults:
    _action: 'handle'
    title: 'Home'

createTask:
  path: /tasks
  controller: App\Controller\Tasks
  methods: ['POST']
  defaults: { _action: 'create' }
  requirements:
    name: '\w+'

TasksList:
  path:
    /tasks/page/{page}
  controller: App\Controller\Tasks
  methods: ['GET']
  defaults:
    _action: 'list'
    page: 1
    title: 'Tasks'
  requirements:
    page: '\d+'
