index:
  path: /
  controller: App\Controller\Home
  methods: ['GET']
  defaults: { _action: 'handle' }

foo:
  path: /foo/{name}
  controller: App\Controller\FooController
  methods: ['GET']
  defaults: { _action: 'handle' }
  requirements:
    name: '\w+'

TasksList:
  path: /tasks/{page}
  controller: App\Controller\Tasks
  methods: ['GET']
  defaults:
    _action: 'list'
    page: 1
  requirements:
    page: '\d+'
